### ISSUE TITLE
Release 2 roadmap

### ISSUE THREAD

**Issue by specificlanguage** [specificlanguage/MoleBot#3]
Features

- [x] /whois - search players on NameMC (ported from CivBot)
- [x]  Database features for config options (such as /disablemole) instead of a lumpy text file
- [ ]  Rail system upgrades
   - [x] Add KANI advisories when looking for nodes
   - [ ] Circular rails
   - [x] Alias support (#6)
   - [ ] Integrate KANI/AURA systems (this is a big if and would probably take a lot of working through aliases)
   - [ ] GOR system (once the above is integrated)
- [ ]  /whereis and /finddest
   - [x] get containing polygon of each point (if possible)
   - [ ] CivMap search 'object' features
- [x] Add hidden messages to most rail dests or whereis commands

Bugs needed fixing
- [x] KANI routing to a junction adds an ':exit' when it's not a stop
- [x] Stop uploading moles and only provide a link to the tenor guf which will improve messaging speeds

May be added sometime in the future (probably not)
- Auction house/find prices for x
- In-game /dest commands

**Comment by specificlanguage** [comment]
Bugs, notices fixed on test, commit 3519039

**Comment by specificlanguage** [comment]
Hidden messages added with commit https://github.com/specificlanguage/MoleBot/commit/d128efd691b682338baa0707b7f825972dfba94d

**Comment by specificlanguage** [comment]
Polygon point added with commit dbe48b9ef3386a7ad0b78559b6e82051be6c1557
More hidden messages (for smaller error messages) added with 09246d520f858c701de6f04ef4d580eb26f0c409

As of right now this commit is on Prod as this was a fix for KANI routing prior to Release 1

**Comment by specificlanguage** [comment]
/whois added in test with https://github.com/specificlanguage/MoleBot/commit/28ae973c153c20c6415827341be579f971216aea

**Comment by specificlanguage** [comment]
Database additions added with commit https://github.com/specificlanguage/MoleBot/commit/f97a7798ee111f6fa2b21e6aa91c8504e151946a

**Comment by specificlanguage** [comment]
More database additions for [[wiki querying]] added with https://github.com/specificlanguage/MoleBot/commit/1bb83457a51fda1964d26e58369f8f4a4e861905
Aliases added with https://github.com/specificlanguage/MoleBot/commit/700ba19dfbbfe38217c5f2292c896701bae46d99

**Comment by specificlanguage** [comment]
Heuristic routing fixed at e7760c6
